sync with master

diff --git a/start-configuration b/start-configuration
--- a/start-configuration
+++ b/start-configuration
@@ -7,8 +7,6 @@ shopt -s nullglob
 #umask 002
 export HOME=/data
 
-log "Running as uid=$(id -u) gid=$(id -g) with /data as '$(ls -lnd /data)'"
-
 if [ ! -e /data/eula.txt ]; then
   if ! isTrue "$EULA"; then
     log ""
@@ -23,6 +21,15 @@ if [ ! -e /data/eula.txt ]; then
   writeEula
 fi
 
+
+log "Running as uid=$(id -u) gid=$(id -g) with /data as '$(ls -lnd /data)'"
+
+if ! touch /data/.verify_access; then
+  log "ERROR: /data doesn't seem to be writable. Please make sure attached directory is writable by uid=$(id -u)"
+  exit 2
+fi
+
+rm /data/.verify_access || true
 
 if [[ $PROXY ]]; then
     export http_proxy="$PROXY"
@@ -95,11 +102,7 @@ case "${TYPE^^}" in
     exec ${SCRIPTS:-/}start-deployFabric "$@"
   ;;
 
-  FTBA)
-    exec ${SCRIPTS:-/}start-deployFTBA "$@"
-  ;;
-
-  CURSEFORGE|FTB)
+  FTB|CURSEFORGE)
     exec ${SCRIPTS:-/}start-deployCF "$@"
   ;;
 
